// AUTO-GENERATED by scripts/extract-entel-the-grid.ts — do not edit by hand.
// Re-run: npx tsx scripts/extract-entel-the-grid.ts
// Galería: poblada por scripts/extract-entel-the-grid-assets.ts (manifest.json).

import type { EntelReport } from "./types";

export const REPORT: EntelReport = {
  "meta": {
    "evento": "The Grid — kiki",
    "marca": "Entel",
    "fecha": "2026-05-09",
    "fechaLarga": "sábado, 9 de mayo de 2026",
    "venue": "Espacio Riesco",
    "responsable": "Glovox",
    "supervisor": "Producción de Marcas",
    "asistentesEstimados": 7000
  },
  "stock": {
    "inicial": 500,
    "metaKpi": 500,
    "reposicion": 0,
    "descuentoManual": 0,
    "ajustado": 500
  },
  "horario": {
    "inicio": "16:30",
    "cierre": "04:45",
    "peakInicio": "19:00",
    "peakTermino": "19:45"
  },
  "kpis": {
    "totalCanjes": 500,
    "stockRestante": 0,
    "pctStockUsado": 1,
    "metaAlcanzada": true,
    "pctAvanceVsMeta": 1,
    "conversionEstimada": 0.07142857142857142,
    "horaMayorDemanda": "19:00"
  },
  "flujoPorHora": [
    {
      "hora": "16:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 500,
      "pctStock": 0,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "16:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 500,
      "pctStock": 0,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "17:00",
      "vasos": 50,
      "canjesAcum": 50,
      "stockRestante": 450,
      "pctStock": 0.09999999999999998,
      "peak": false,
      "condicion": "Flujo bajo — inicio",
      "observacion": "17:00–17:30: se entregan los primeros 50 vasos. Público comienza a llegar de forma paulatina. Operación ordenada. Titular presenta cupón físico para canjear.",
      "fotos": [],
      "validadoPor": "Glovox"
    },
    {
      "hora": "17:30",
      "vasos": 100,
      "canjesAcum": 100,
      "stockRestante": 350,
      "pctStock": 0.30000000000000004,
      "peak": false,
      "condicion": "Flujo moderado",
      "observacion": "17:30–18:30: se entregan 100 vasos. Flujo constante y estable. Fila manejable. Sin incidentes. Público receptivo al beneficio.",
      "fotos": [],
      "validadoPor": "Glovox"
    },
    {
      "hora": "18:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 350,
      "pctStock": 0.30000000000000004,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "18:30",
      "vasos": 100,
      "canjesAcum": 100,
      "stockRestante": 250,
      "pctStock": 0.5,
      "peak": false,
      "condicion": "Flujo creciente",
      "observacion": "18:30–19:00: se entregan 100 vasos. El flujo de público aumenta progresivamente hacia el horario peak. La fila comienza a extenderse de forma visible.",
      "fotos": [
        "1830_fila_01.jpg"
      ],
      "validadoPor": "Glovox"
    },
    {
      "hora": "19:00",
      "vasos": 150,
      "canjesAcum": 150,
      "stockRestante": 100,
      "pctStock": 0.8,
      "peak": true,
      "condicion": "PEAK — Flujo muy alto",
      "observacion": "19:00–19:45: se entregan 150 vasos. HORARIO PEAK. Alta concentración de demanda. La fila se desbarata — se forman 2 colas simultáneas sin control. La fila era tan larga que comenzó a tapar la visibilidad de las barras aledañas. Se actuó en el momento improvisando una solución sin protocolo previo. El cupón dejó de validarse correctamente: parte del público comienza a mostrar fotos del cupón en pantalla, pasando de mano en mano. Clientes no titulares de Entel accedieron al beneficio. Contradicción de la marca: instrucción en terreno era solo el TITULAR puede canjear, pero la app Entel indicaba que el beneficio se podía REGALAR. Alta disconformidad del público.",
      "fotos": [
        "1900_peak_fila_01.jpg",
        "1900_peak_fila_02.jpg"
      ],
      "validadoPor": "Glovox"
    },
    {
      "hora": "19:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 100,
      "pctStock": 0.8,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "20:00",
      "vasos": 100,
      "canjesAcum": 100,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": "Stock agotándose — cierre activación",
      "observacion": "19:45–20:40: se entrega el stock restante de 100 vasos de forma progresiva. A las 20:40 hrs se confirma el AGOTAMIENTO TOTAL del stock (500 vasos entregados). Público que llegó posterior a este horario no pudo acceder al beneficio, generando disconformidad. Sin stock de contingencia disponible.",
      "fotos": [
        "2040_sin_stock_01.jpg"
      ],
      "validadoPor": "Glovox"
    },
    {
      "hora": "20:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "21:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "21:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "22:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "22:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": "Sin stock — público tardío sin beneficio",
      "observacion": "22:30–23:00: asistentes de entrada general buscan activamente la activación Entel y no encuentran beneficio disponible. Percepción de abandono de marca en el tramo de cierre del evento. Se registra disconformidad del público tardío.",
      "fotos": [],
      "validadoPor": "Glovox"
    },
    {
      "hora": "23:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "23:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "00:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "00:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "01:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "01:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "02:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "02:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "03:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "03:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "04:00",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    },
    {
      "hora": "04:30",
      "vasos": 0,
      "canjesAcum": 0,
      "stockRestante": 0,
      "pctStock": 1,
      "peak": false,
      "condicion": null,
      "observacion": null,
      "fotos": [],
      "validadoPor": null
    }
  ],
  "flujoAgrupado": [
    {
      "hora": "17:00",
      "vasos": 50,
      "peak": false
    },
    {
      "hora": "17:30",
      "vasos": 100,
      "peak": false
    },
    {
      "hora": "18:30",
      "vasos": 100,
      "peak": false
    },
    {
      "hora": "19:00",
      "vasos": 200,
      "peak": true
    },
    {
      "hora": "20:00",
      "vasos": 50,
      "peak": false
    },
    {
      "hora": "21:15+",
      "vasos": 0,
      "peak": false
    }
  ],
  "incidentes": [
    {
      "hora": "19:00",
      "tipo": "Logística",
      "descripcion": "Fila descontrolada — se formaron 2 colas simultáneas durante el peak. La fila era tan larga que tapaba la visibilidad de las barras aledañas.",
      "accionTomada": "Se actuó improvisando en el momento para encauzar la fila. Sin protocolo previo.",
      "seguimiento": "Próximo evento: 2 personas exclusivas de control de fila 19:00–21:00. Protocolo escrito antes del evento."
    },
    {
      "hora": "19:15",
      "tipo": "Seguridad",
      "descripcion": "Fraude con cupón digital: el cupón circuló de mano en mano (fotos en pantalla). Clientes NO Entel accedieron al beneficio.",
      "accionTomada": "Imposible controlar con el flujo existente. Se siguió entregando para evitar conflictos mayores.",
      "seguimiento": "Entel debe implementar QR único por cliente que se invalide al primer uso. Integrar el canje en la app."
    },
    {
      "hora": "19:00",
      "tipo": "Quejas",
      "descripcion": "Contradicción en instrucciones: se pedía que solo el TITULAR canjeara, pero la app de Entel decía que el beneficio se podía REGALAR. Alta disconformidad del cliente.",
      "accionTomada": "Se explicó la situación pero sin respaldo claro, generando mayor tensión.",
      "seguimiento": "Entel debe alinear su comunicación interna: si el beneficio es intransferible, la app no puede decir lo contrario."
    },
    {
      "hora": "20:40",
      "tipo": "Stock",
      "descripcion": "Stock de vasos AGOTADO a las 20:40 hrs. Asistentes restantes sin poder canjear.",
      "accionTomada": "Se informó al público que el stock estaba agotado. Fin de la activación.",
      "seguimiento": "Evaluar si 500 vasos es suficiente para el flujo real del evento. Considerar stock de contingencia."
    },
    {
      "hora": "Todo el evento",
      "tipo": "Oportunidad",
      "descripcion": "El vaso ya no sorprende al cliente. Por ser un beneficio repetido en múltiples fechas de Piknic, el cliente lo percibe como obligación de la marca, no como un premio.",
      "accionTomada": "Observación registrada para análisis estratégico.",
      "seguimiento": "Variar el tipo de beneficio por fecha. Mantener la sorpresa es clave para que el cliente se sienta realmente premiado."
    },
    {
      "hora": "19:45",
      "tipo": "Stock / Vasos",
      "descripcion": "Agotamiento progresivo del stock de vasos entre las 19:45 y las 20:40 hrs. El público que llegó en el tramo horario tardío (22:30–23:00 hrs), correspondiente principalmente a la entrada general sin límite de horario, no pudo acceder al beneficio al encontrarse el stock completamente agotado.",
      "accionTomada": "Se informó al público del agotamiento. Sin stock de contingencia disponible.",
      "seguimiento": "Evaluar un stock de contingencia reservado para el tramo horario 22:00–23:30, especialmente si el evento contempla dos tipos de entrada (con límite horario y entrada general). Alternativamente, considerar una activación diferente para el público tardío que no dependa del stock de vasos."
    },
    {
      "hora": "22:30",
      "tipo": "Experiencia cliente — Horario tardío",
      "descripcion": "Asistentes que llegaron en el tramo 22:30–23:00 hrs (entrada general sin límite horario) buscaron activamente la activación Entel y no encontraron beneficio disponible. La percepción fue de abandono de la marca en el tramo más concurrido del cierre del evento.",
      "accionTomada": "No se contaba con protocolo ni activación alternativa para este segmento horario.",
      "seguimiento": "Diseñar una activación específica para el segmento de público que llega después de las 22:00 hrs. Puede ser una dinámica digital (código QR, descarga de app, encuesta) que no dependa de stock físico y mantenga al cliente comprometido con la marca."
    }
  ],
  "guardarropia": {
    "timeline": [
      {
        "hora": "16:30",
        "cuposGuardados": null,
        "cuposAcum": 0,
        "stockRestante": 200,
        "condicion": "Normal",
        "observacion": "Apertura del servicio de guardarropía. Sin demanda inicial."
      },
      {
        "hora": "17:00",
        "cuposGuardados": null,
        "cuposAcum": 0,
        "stockRestante": 200,
        "condicion": "Normal",
        "observacion": "Sin movimiento. Público aún no ha llegado en masa."
      },
      {
        "hora": "17:30",
        "cuposGuardados": null,
        "cuposAcum": 0,
        "stockRestante": 200,
        "condicion": "Normal",
        "observacion": "Flujo reducido. Guardarropía habilitada y lista."
      },
      {
        "hora": "18:00",
        "cuposGuardados": null,
        "cuposAcum": 0,
        "stockRestante": 200,
        "condicion": "Normal",
        "observacion": "Sin registros en este tramo."
      },
      {
        "hora": "18:30",
        "cuposGuardados": 84,
        "cuposAcum": 84,
        "stockRestante": 116,
        "condicion": "Flujo moderado",
        "observacion": "18:30–19:00: se guardan los primeros 84 cupos. Operación fluida."
      },
      {
        "hora": "19:00",
        "cuposGuardados": null,
        "cuposAcum": 84,
        "stockRestante": 116,
        "condicion": "Flujo moderado",
        "observacion": "Sin registros adicionales en este tramo."
      },
      {
        "hora": "19:30",
        "cuposGuardados": null,
        "cuposAcum": 84,
        "stockRestante": 116,
        "condicion": "Flujo moderado",
        "observacion": "Sin registros adicionales en este tramo."
      },
      {
        "hora": "20:00",
        "cuposGuardados": 16,
        "cuposAcum": 100,
        "stockRestante": 100,
        "condicion": "Flujo alto",
        "observacion": "20:00: se alcanzan los 100 cupos guardados. Aumenta la demanda."
      },
      {
        "hora": "20:30",
        "cuposGuardados": null,
        "cuposAcum": 100,
        "stockRestante": 100,
        "condicion": "Flujo alto",
        "observacion": "Sin registros adicionales en este tramo."
      },
      {
        "hora": "21:00",
        "cuposGuardados": null,
        "cuposAcum": 100,
        "stockRestante": 100,
        "condicion": "Flujo alto",
        "observacion": "Sin registros adicionales en este tramo."
      },
      {
        "hora": "21:15",
        "cuposGuardados": 50,
        "cuposAcum": 150,
        "stockRestante": 50,
        "condicion": "Flujo muy alto",
        "observacion": "21:15: se alcanzan los 150 cupos. La demanda se intensifica."
      },
      {
        "hora": "21:30",
        "cuposGuardados": null,
        "cuposAcum": 150,
        "stockRestante": 50,
        "condicion": "Flujo muy alto",
        "observacion": "Sin registros adicionales en este tramo."
      },
      {
        "hora": "21:37",
        "cuposGuardados": 23,
        "cuposAcum": 173,
        "stockRestante": 27,
        "condicion": "Flujo moderado",
        "observacion": null
      },
      {
        "hora": "22:00",
        "cuposGuardados": null,
        "cuposAcum": 173,
        "stockRestante": 27,
        "condicion": "Flujo alto",
        "observacion": "Sin registros adicionales en este tramo."
      },
      {
        "hora": "22:30",
        "cuposGuardados": null,
        "cuposAcum": 173,
        "stockRestante": 27,
        "condicion": "Flujo alto",
        "observacion": "Sin registros adicionales en este tramo."
      },
      {
        "hora": "22:47",
        "cuposGuardados": 67,
        "cuposAcum": 200,
        "stockRestante": 0,
        "condicion": "STOCK AGOTADO",
        "observacion": "22:47: se guardan los últimos 67 cupos. Stock totalmente agotado (200/200)."
      }
    ],
    "evaluacion": [
      {
        "aspecto": "Estado final",
        "detalle": "Stock de 200 cupos agotado a las 22:47 hrs. La totalidad de los cupos fue utilizada, lo que confirma alta demanda del servicio."
      },
      {
        "aspecto": "Problema principal",
        "detalle": "Al finalizar el evento, se generó una fila de espera de aproximadamente 1 hora para la devolución de prendas. La fila no contó con un sistema de orden efectivo: se registraron múltiples incidencias de personas que se colaron y no respetaron el turno de espera, generando molestia generalizada entre los clientes."
      },
      {
        "aspecto": "Impacto en experiencia del cliente",
        "detalle": "El cliente Entel, que recibió el cupo de guardarropía como beneficio de la marca, no recuerda el regalo al momento del retiro. Lo que perdura en su memoria es la experiencia final: una fila desordenada, sin control y con espera de hasta 1 hora. Este factor daña directamente la percepción de la marca Entel, independientemente del valor del beneficio entregado."
      },
      {
        "aspecto": "Personal insuficiente",
        "detalle": "El equipo asignado a guardarropía no fue suficiente para gestionar el volumen de retiros concentrado al cierre del evento. No se activó refuerzo de personal durante el peak de salida."
      }
    ],
    "recomendaciones": [
      {
        "n": 1,
        "problema": "Fila desordenada al cierre del evento con espera de ~1 hora",
        "solucion": "Implementar sistema de retiro por turnos o números de ticket. Designar al menos 2 personas exclusivamente para el control y orden de la fila durante el cierre (03:00 en adelante).",
        "prioridad": "ALTA",
        "responsable": "Operaciones / Supervisor de guardarropía",
        "plazo": "Próximo evento"
      },
      {
        "n": 2,
        "problema": "Personal insuficiente en el peak de retiro",
        "solucion": "Reforzar el equipo de guardarropía a partir de las 03:00 hrs, anticipando el peak de retiro al cierre del evento. Mínimo 2 personas adicionales en el tramo 03:00–cierre.",
        "prioridad": "ALTA",
        "responsable": "Coordinación Entel",
        "plazo": "Próximo evento"
      },
      {
        "n": 3,
        "problema": "Sin diferenciación para clientes Entel en la fila",
        "solucion": "Habilitar una fila o zona exclusiva de atención para titulares del beneficio Entel. Esto refuerza la percepción de privilegio del cliente y mejora la experiencia final.",
        "prioridad": "MEDIA",
        "responsable": "Entel / Operaciones",
        "plazo": "Próximo evento"
      },
      {
        "n": 4,
        "problema": "Alta concentración de retiros al cierre",
        "solucion": "Considerar la posibilidad de incentivar retiros anticipados a través de comunicación en el evento (anuncio por micrófono o pantalla) a partir de las 21:00 hrs, para distribuir el flujo.",
        "prioridad": "MEDIA",
        "responsable": "Producción del evento",
        "plazo": "Próximo evento"
      }
    ]
  },
  "objetivosEntel": [
    {
      "titulo": "Fidelización",
      "pregunta": "¿Canjearon los clientes Entel?",
      "resultado": "SÍ. La totalidad de los clientes Entel presentes canjearon su beneficio, con una tasa de uso del 100% del stock. La marca logró un contacto directo y tangible con su base de clientes durante el evento, reforzando el vínculo entre Entel y los momentos de entretenimiento de sus usuarios.",
      "alcanzado": "si",
      "detalle": "La totalidad de los clientes Entel canjearon su beneficio con una tasa de uso del 100% del stock, reforzando el vínculo entre la marca y los momentos de entretenimiento de sus usuarios."
    },
    {
      "titulo": "Captación",
      "pregunta": "¿Hubo descargas de app o registros?",
      "resultado": "En esta edición no se implementó un mecanismo formal de captación de nuevos clientes. Se identifica como oportunidad para próximas activaciones: integrar una acción digital (descarga de app, registro o encuesta) como parte del proceso de canje, lo que permitiría ampliar el alcance de la activación más allá del evento presencial.",
      "alcanzado": "proyeccion",
      "detalle": "En esta edición no se implementó un mecanismo formal de captación de nuevos clientes. Se identifica como oportunidad para próximas activaciones: integrar una acción digital (descarga de app, registro o encuesta) como parte del proceso de canje, lo que permitiría ampliar el alcance de la activación más allá del evento presencial."
    },
    {
      "titulo": "Visibilidad",
      "pregunta": "¿Generamos alcance en RRSS?",
      "resultado": "SÍ. La presencia de Entel fue sostenida y visible durante el evento, con un stand activo y una distribución de beneficios de alto impacto. La marca logró diferenciarse en un entorno competitivo, donde la ausencia de Entel habría dejado ese espacio a la competencia. La visibilidad generada en el tramo peak (19:00–20:00 hrs) representó el momento de mayor exposición de marca durante la jornada.",
      "alcanzado": "si",
      "detalle": "SÍ. La presencia de Entel fue sostenida y visible durante el evento, con un stand activo y una distribución de beneficios de alto impacto. La marca logró diferenciarse en un entorno competitivo, donde la ausencia de Entel habría dejado ese espacio a la competencia. La visibilidad generada en el tramo peak (19:00–20:00 hrs) representó el momento de mayor exposición de marca durante la jornada."
    }
  ],
  "cualitativo": {
    "queFunciono": [
      {
        "icon": "🥤",
        "titulo": "Stock distribuido al 100%",
        "detalle": "La totalidad de los 500 vasos fue retirada, evidenciando alta penetración y participación activa de la base de clientes Entel presentes en el evento.",
        "tone": "positive"
      },
      {
        "icon": "👁",
        "titulo": "Visibilidad de marca sostenida",
        "detalle": "Presencia activa durante todo el tramo peak del evento. La marca Entel logró diferenciarse en un entorno competitivo con alta convocatoria, consolidando su posicionamiento frente a la competencia.",
        "tone": "positive"
      },
      {
        "icon": "⚡",
        "titulo": "Flexibilidad del equipo en terreno",
        "detalle": "El equipo demostró capacidad de respuesta y adaptabilidad ante la alta demanda, manteniendo la operación activa y sin interrupciones durante todo el horario peak.",
        "tone": "positive"
      },
      {
        "icon": "🎯",
        "titulo": "Meta KPI alcanzada al 100%",
        "detalle": "Los 500 canjes objetivo fueron completados en su totalidad, consolidando la fidelización de clientes Entel en uno de los eventos musicales de mayor convocatoria del período.",
        "tone": "positive"
      }
    ],
    "proyecciones": [
      {
        "icon": "🚦",
        "titulo": "Protocolo de control de fila en peak",
        "detalle": "Para maximizar la experiencia en el horario 19:00–21:00, se proyecta incorporar personal dedicado exclusivamente al encauzamiento del flujo y señalización de acceso.",
        "tone": "projection"
      },
      {
        "icon": "📱",
        "titulo": "Integración digital del proceso de canje",
        "detalle": "Se proyecta unificar la experiencia de canje a través de un QR único por cliente integrado en la app Entel, reforzando la trazabilidad y exclusividad del beneficio.",
        "tone": "projection"
      },
      {
        "icon": "🌙",
        "titulo": "Activación digital para el tramo tardío",
        "detalle": "Se proyecta diseñar una experiencia de marca complementaria para el tramo 22:00–23:30, sin dependencia de stock físico, que mantenga el vínculo con el público de entrada general.",
        "tone": "projection"
      },
      {
        "icon": "🧥",
        "titulo": "Optimización del cierre de guardarropía",
        "detalle": "Se proyecta incorporar un sistema de tickets numerados y personal de refuerzo a partir de las 03:00 hrs, para garantizar una experiencia de retiro de prendas fluida y sin esperas.",
        "tone": "projection"
      }
    ]
  },
  "recomendaciones": [
    {
      "numero": "01",
      "titulo": "Control de fila en peak",
      "detalle": "2 personas dedicadas al control de fila en 19:00–21:00 hrs. Protocolo escrito previo al evento con separadores físicos y señalización clara.",
      "prioridad": "Alta"
    },
    {
      "numero": "02",
      "titulo": "QR único por cliente",
      "detalle": "QR vinculado al RUT o cuenta Entel, invalidado tras el primer canje. Integrar directamente en la app oficial para mayor trazabilidad.",
      "prioridad": "Alta"
    },
    {
      "numero": "03",
      "titulo": "Unificación de comunicación",
      "detalle": "Alinear los mensajes de la app Entel con las instrucciones en terreno antes de cada evento. Respaldo escrito y oficial para el equipo.",
      "prioridad": "Alta"
    },
    {
      "numero": "04",
      "titulo": "Activación para público tardío",
      "detalle": "Experiencia digital para el tramo 22:00–23:30 que no dependa de stock físico: QR con beneficio digital, sorteo vía RRSS o dinámica de captación.",
      "prioridad": "Media"
    },
    {
      "numero": "05",
      "titulo": "Guardarropía · Sistema de tickets",
      "detalle": "Tickets numerados para retiro y personal de refuerzo desde las 03:00 hrs. Zona diferenciada y exclusiva para titulares del beneficio Entel.",
      "prioridad": "Alta"
    },
    {
      "numero": "06",
      "titulo": "Variación del beneficio",
      "detalle": "Rotar el tipo de beneficio por fecha para mantener el factor sorpresa y que el cliente siempre perciba la activación Entel como un premio exclusivo.",
      "prioridad": "Media"
    }
  ],
  "solucionesPropuestas": [
    {
      "titulo": "✔  Control de fila en período peak (19:00–19:45)",
      "detalle": "Asignar 2 personas dedicadas exclusivamente al control de fila en el tramo 19:00–21:00 hrs. Establecer un protocolo escrito de gestión de fila antes del evento, con separadores físicos y señalización clara."
    },
    {
      "titulo": "✔  Fraude con cupón digital",
      "detalle": "Implementar un sistema de QR único por cliente, vinculado a su RUT o cuenta Entel, que se invalide tras el primer canje. Integrar el canje directamente en la app oficial de Entel para trazabilidad completa."
    },
    {
      "titulo": "✔  Contradicción en instrucciones de canje",
      "detalle": "Alinear la comunicación interna de Entel antes de cada evento: si el beneficio es intransferible, la app y todos los canales de comunicación deben indicarlo de forma consistente. El equipo en terreno debe contar con un respaldo escrito y oficial de las instrucciones de canje."
    },
    {
      "titulo": "✔  Vaso como beneficio repetido sin sorpresa",
      "detalle": "Variar el tipo de beneficio por fecha o evento. Complementar el vaso con una dinámica interactiva (sorteo, concurso, experiencia digital) que genere valor emocional adicional y percepción de exclusividad. El objetivo es que el cliente se sienta premiado, no que sienta que está cobrando lo que le corresponde."
    },
    {
      "titulo": "✔  Público tardío sin activación (22:30–23:00)",
      "detalle": "Diseñar una activación específica para el tramo de cierre que no dependa de stock físico. Opciones: descuento digital mediante QR, beneficio en app, sorteo vía RRSS o dinámica de captación de datos que además genere valor para la marca."
    },
    {
      "titulo": "✔  Guardarropía sin orden al cierre",
      "detalle": "Incorporar personal de refuerzo en guardarropía a partir de las 03:00 hrs. Habilitar zona diferenciada para clientes Entel. Implementar sistema de tickets de retiro para eliminar la formación de filas prolongadas. Comunicar anticipadamente el cierre del servicio para distribuir el flujo de retiro."
    }
  ],
  "timeline": [
    {
      "hora": "16:00",
      "tag": "Apertura",
      "tone": "sky",
      "texto": "Apertura del evento y habilitación del punto de canje Entel. Equipo en posición, materiales listos, guardarropía operativa desde las 16:30 hrs."
    },
    {
      "hora": "17:00",
      "tag": "Flujo bajo",
      "tone": "blue",
      "texto": "Se entregan los primeros 50 vasos. El público comienza a llegar de forma paulatina. Operación ordenada, equipo activo y público receptivo al beneficio."
    },
    {
      "hora": "17:30",
      "tag": "Flujo moderado",
      "tone": "blue",
      "texto": "Se entregan 100 vasos. Flujo constante y estable. Fila manejable. Sin incidentes. Público receptivo al beneficio Entel."
    },
    {
      "hora": "18:30",
      "tag": "Flujo creciente",
      "tone": "blue",
      "texto": "Se entregan 100 vasos adicionales. El flujo de público aumenta progresivamente hacia el horario peak. La activación mantiene un ritmo de entrega ágil y ordenado."
    },
    {
      "hora": "19:00",
      "tag": "Peak · Máxima demanda",
      "tone": "orange",
      "texto": "Se entregan 200 vasos en el horario de mayor concentración de público. La activación alcanza su punto de mayor visibilidad e impacto. El equipo en terreno responde con flexibilidad sosteniendo la operación en pleno peak."
    },
    {
      "hora": "20:00",
      "tag": "Descenso progresivo",
      "tone": "blue",
      "texto": "Se distribuyen los últimos 50 vasos de forma progresiva. El flujo de público se estabiliza. La activación mantiene presencia activa y visible en el recinto."
    },
    {
      "hora": "21:15",
      "tag": "Cierre exitoso",
      "tone": "success",
      "texto": "Se confirma la distribución total de los 500 vasos. Activación cerrada exitosamente con el 100% del stock entregado."
    },
    {
      "hora": "22:47",
      "tag": "Guardarropía · Cierre",
      "tone": "sky",
      "texto": "Los 200 cupos de guardarropía son completamente utilizados. Servicio operativo durante toda la jornada con alta demanda sostenida."
    },
    {
      "hora": "23:00",
      "tag": "Post-activación",
      "tone": "gray",
      "texto": "Cierre del evento. La presencia de Entel fue sostenida y visible durante toda la jornada. Oportunidad: complementar futuras ediciones con activación digital para el tramo de cierre."
    }
  ],
  "galeria": [
    {
      "src": "/reports/entel-the-grid/gallery/01.jpg",
      "caption": "Activación Entel — punto de canje",
      "span": "tall"
    },
    {
      "src": "/reports/entel-the-grid/gallery/02.jpg",
      "caption": "Distribución de vasos Entel"
    },
    {
      "src": "/reports/entel-the-grid/gallery/03.jpg",
      "caption": "Equipo en terreno"
    },
    {
      "src": "/reports/entel-the-grid/gallery/04.jpg",
      "caption": "Flujo de público"
    },
    {
      "src": "/reports/entel-the-grid/gallery/05.jpg",
      "caption": "Stand Entel en horario peak"
    },
    {
      "src": "/reports/entel-the-grid/gallery/06.jpg",
      "caption": "Operación general del evento",
      "span": "wide"
    },
    {
      "src": "/reports/entel-the-grid/gallery/07.jpg",
      "caption": "Control de acceso al beneficio"
    },
    {
      "src": "/reports/entel-the-grid/gallery/08.jpg",
      "caption": "Activación en alta demanda"
    },
    {
      "src": "/reports/entel-the-grid/gallery/09.jpg",
      "caption": "Público participante"
    },
    {
      "src": "/reports/entel-the-grid/gallery/10.jpg",
      "caption": "Vista general — Espacio Riesco",
      "span": "tall"
    },
    {
      "src": "/reports/entel-the-grid/gallery/11.jpg",
      "caption": "Canje de beneficio Entel"
    },
    {
      "src": "/reports/entel-the-grid/gallery/12.jpg",
      "caption": "Dinámica de activación"
    },
    {
      "src": "/reports/entel-the-grid/gallery/13.jpg",
      "caption": "Momento de entrega"
    },
    {
      "src": "/reports/entel-the-grid/gallery/14.jpg",
      "caption": "Guardarropía Entel"
    },
    {
      "src": "/reports/entel-the-grid/gallery/15.jpg",
      "caption": "Cierre de activación"
    }
  ],
  "conclusionEjecutiva": "La activación Entel en The Grid — kiki fue exitosa. El 100% del stock fue distribuido antes de las 21:15 hrs, la visibilidad de marca se mantuvo sostenida durante todo el peak y el equipo respondió con flexibilidad ante la alta demanda. Las proyecciones identificadas fortalecerán las próximas ediciones."
};
